p8105_hw2_Coo2124
================

\#Problem1

``` r
data1 <- read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
transit_new <- data1 %>%
  select(Line, `Station Name`, `Station Latitude`, `Station Longitude`, Route1:Route11, Entry, Vending, `Entrance Type`, ADA) %>%
  mutate(across(starts_with("Route8"):starts_with("Route11"), as.character),
         Entry = ifelse(Entry == "YES", TRUE, FALSE)) %>%
  pivot_longer(cols = starts_with("Route"),
               names_to = "Route_Number",   
               values_to = "Route") %>%
  distinct()

dim(transit_new)
```

    ## [1] 7504   10

``` r
str(transit_new)
```

    ## tibble [7,504 × 10] (S3: tbl_df/tbl/data.frame)
    ##  $ Line             : chr [1:7504] "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ Station Name     : chr [1:7504] "25th St" "25th St" "25th St" "25th St" ...
    ##  $ Station Latitude : num [1:7504] 40.7 40.7 40.7 40.7 40.7 ...
    ##  $ Station Longitude: num [1:7504] -74 -74 -74 -74 -74 ...
    ##  $ Entry            : logi [1:7504] TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ Vending          : chr [1:7504] "YES" "YES" "YES" "YES" ...
    ##  $ Entrance Type    : chr [1:7504] "Stair" "Stair" "Stair" "Stair" ...
    ##  $ ADA              : logi [1:7504] FALSE FALSE FALSE FALSE FALSE FALSE ...
    ##  $ Route_Number     : chr [1:7504] "Route1" "Route2" "Route3" "Route4" ...
    ##  $ Route            : chr [1:7504] "R" NA NA NA ...

The NYC Transit dataset contains rows and columns, giving us detailed
info about subway entrances and exits. Key variables include `line`,
`station_name`, `latitude`, `longitude`, `routes_served`, `entry`,
`vending`, `entrance_type`, and `ADA_compliance`. I converted entry from
a character format `("YES"/"NO")` to a logical format `(TRUE/FALSE)`
using `ifelse` in R. For cleaning, I kept only the relevant columns
mentioned above. The data looks tidy—each row is one observation of an
entrance or exit, with each variable neatly in its own column.

\#1. How many distinct stations are there?

``` r
distinct_stations <- transit_new %>%
  distinct(Line, `Station Name`) %>%
  count()
print(distinct_stations)
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1   465

\#answer: There are 465 distinct stations

\#2.How many stations are ADA compliant?

``` r
ada_compliant_stations_count <- transit_new %>%
  filter(ADA == TRUE) %>%                         
  distinct(Line, `Station Name`) %>%                 
  nrow()                                           

print(ada_compliant_stations_count)
```

    ## [1] 84

\#answer:There are 84 station in ADA compliant

\#3.What proportion of station entrances / exits without vending allow
entrance?

``` r
proportion_no_vending_entry <- transit_new %>%
  filter(Vending == "NO") %>%                      
  summarise(Proportion = mean(Entry == TRUE, na.rm = TRUE)) 

print(proportion_no_vending_entry)
```

    ## # A tibble: 1 × 1
    ##   Proportion
    ##        <dbl>
    ## 1      0.385

\#answer: The proportion of station entrances/exits without vending that
allow entrance is 38%.

\#Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train?

``` r
data1[, paste0("Route", 8:11)] <- lapply(data1[, paste0("Route", 8:11)], as.character)

distinct_a_stations <- data1 %>%
  pivot_longer(
    cols = Route1:Route11,             
    names_to = "route_num",           
    values_to = "route"              
  ) %>%
  filter(route == "A") %>%
  select(`Station Name`, Line) %>%  
  distinct()

nrow(distinct_a_stations)
```

    ## [1] 60

\#answer: There are 60 distinct stations that serve the A train in the
NYC subway system.

\#Of the stations that serve the A train, how many are ADA compliant?

``` r
distinct_a_stations_ada <- data1 %>%
  pivot_longer(
    cols = Route1:Route11,
    names_to = "route_num",
    values_to = "route"
  ) %>%
  filter(route == "A", ADA == TRUE) %>%  
  select(`Station Name`, Line) %>%
  distinct()

nrow(distinct_a_stations_ada)
```

    ## [1] 17

\#answer:Of the stations that serve the A train, 17 stations are ADA
compliant.

\#Problem 2 \#Read and clean the Mr. Trash Wheel dataset

``` r
library(readxl)
problem2 <- read_excel("202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
head(problem2)
```

    ## # A tibble: 6 × 16
    ##   Dumpster Month Year  Date                `Weight (tons)`
    ##      <dbl> <chr> <chr> <dttm>                        <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00            4.31
    ## 2        2 May   2014  2014-05-16 00:00:00            2.74
    ## 3        3 May   2014  2014-05-16 00:00:00            3.45
    ## 4        4 May   2014  2014-05-17 00:00:00            3.1 
    ## 5        5 May   2014  2014-05-17 00:00:00            4.06
    ## 6        6 May   2014  2014-05-20 00:00:00            2.71
    ## # ℹ 11 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>, ...15 <lgl>, ...16 <lgl>

``` r
mr_trash <- problem2 %>%
  select(Dumpster, Month, Year, Date, `Weight (tons)`, `Plastic Bottles`, 
         `Cigarette Butts`, `Plastic Bags`, `Sports Balls`) %>%
  mutate(Year =  as.character(Year))
mr_trash$`Sports Balls` <- as.integer(round(mr_trash$`Sports Balls`))
mr_trash <- mr_trash %>%
  slice(1:(n() - 2)) 
```

\#Read and clean the Professor Trash Wheel dataset

``` r
problem2_1 <- read_excel("202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel")

professor_trash <- problem2_1 %>%
  select(Dumpster, Month, Year, Date, `Weight (tons)`, `Plastic Bottles`, 
         `Cigarette Butts`, `Plastic Bags`, Wrappers) %>%
  mutate(Year = as.character(Year))
professor_trash <- professor_trash %>%
  slice(1:(n() - 3))
```

\#Read and clean the Gwynnda dataset

``` r
problem2_2 <- read_excel("202409 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel")

gwynnda_trash <- problem2_2 %>%
  select(Dumpster, Month, Year, Date, `Weight (tons)`, `Plastic Bottles`, 
         `Cigarette Butts`, `Plastic Bags`, Wrappers) %>%
  mutate(Year = as.character(Year))
gwynnda_trash <- gwynnda_trash %>%
  slice(1:(n() - 1))
```

\#Combine the datasets

``` r
mr_trash <- mr_trash %>% mutate(source = "Mr. Trash")
professor_trash <- professor_trash %>% mutate(source = "Professor Trash")
gwynnda_trash <- gwynnda_trash %>% mutate(source = "Gwynnda Trash")
```

# Combine the datasets into a single tidy dataset

``` r
combined_trash_data <- bind_rows(mr_trash, professor_trash, gwynnda_trash)
dim(combined_trash_data)
```

    ## [1] 1032   11

``` r
total_weight_professor_trash <- combined_trash_data %>%
  filter(source == "Professor Trash") %>%
  summarize(total_weight = sum(`Weight (tons)`, na.rm = TRUE))

print(total_weight_professor_trash)
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         247.

``` r
total_cigarette_butts <- combined_trash_data %>%
  filter(source == "Gwynnda Trash") %>%
  summarize(total_cigarette = sum(`Cigarette Butts`, na.rm = TRUE))

print(total_cigarette_butts)
```

    ## # A tibble: 1 × 1
    ##   total_cigarette
    ##             <dbl>
    ## 1          623920

The combined dataset from Mr. Trash Wheel, Professor Trash Wheel, and
Gwynnda consists of 1032 observations. It includes key variables such as
Date, Dumpster, total_weight (the weight of trash in tons), sports_balls
(the number of sports balls collected), and cigarette_butts (the number
of cigarette butts collected). Each observation corresponds to the trash
collected by one of the trash wheels on a specific date. For example,
Professor Trash Wheel collected a total of 246.74 tons of trash, while
Gwynnda collected 6.2392^{5} cigarette butts in June 2022. These data
provide a detailed look at the significant efforts of these trash wheels
in reducing waste in the Baltimore harbor.

\#Problem 3 \#Import the datasets

``` r
bakers <- read_csv("gbb_datasets/bakers.csv")
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes <- read_csv("gbb_datasets/bakes.csv")
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results <- read_csv("gbb_datasets/results.csv", skip = 2)
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

\#check variable types - everything looks good

``` r
str(bakers)
```

    ## spc_tbl_ [120 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Baker Name      : chr [1:120] "Ali Imdad" "Alice Fevronia" "Alvin Magallanes" "Amelia LeBruin" ...
    ##  $ Series          : num [1:120] 4 10 6 10 7 1 9 4 2 7 ...
    ##  $ Baker Age       : num [1:120] 25 28 37 24 25 30 30 31 31 23 ...
    ##  $ Baker Occupation: chr [1:120] "Charity worker" "Geography teacher" "Nurse" "Fashion designer" ...
    ##  $ Hometown        : chr [1:120] "Saltley, Birmingham" "Essex" "Bracknell, Berkshire" "Halifax" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   `Baker Name` = col_character(),
    ##   ..   Series = col_double(),
    ##   ..   `Baker Age` = col_double(),
    ##   ..   `Baker Occupation` = col_character(),
    ##   ..   Hometown = col_character()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
bakers <- bakers %>%
  rename(baker_name = `Baker Name`,
         series = Series,
         baker_age = `Baker Age`,
         baker_occupation = `Baker Occupation`,
         hometown = Hometown)
```

``` r
str(bakes)
```

    ## spc_tbl_ [548 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Series        : num [1:548] 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ Episode       : num [1:548] 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ Baker         : chr [1:548] "Annetha" "David" "Edd" "Jasminder" ...
    ##  $ Signature Bake: chr [1:548] "Light Jamaican Black Cakewith Strawberries and Cream" "Chocolate Orange Cake" "Caramel Cinnamon and Banana Cake" "Fresh Mango and Passion Fruit Hummingbird Cake" ...
    ##  $ Show Stopper  : chr [1:548] "Red, White & Blue Chocolate Cake with Cigarellos, Fresh Fruit, and Cream" "Black Forest Floor Gateauxwith Moulded Chocolate Leaves, Fallen Fruitand Chocolate Mushrooms Moulded from eggs" "N/A" "N/A" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Series = col_double(),
    ##   ..   Episode = col_double(),
    ##   ..   Baker = col_character(),
    ##   ..   `Signature Bake` = col_character(),
    ##   ..   `Show Stopper` = col_character()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
bakes <- bakes %>%
  rename(series = Series,
         episode = Episode,
         baker = Baker,
         signature_bake = `Signature Bake`,
         show_stopper = `Show Stopper`)
```

``` r
str(results)
```

    ## spc_tbl_ [1,136 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ series   : num [1:1136] 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ episode  : num [1:1136] 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ baker    : chr [1:1136] "Annetha" "David" "Edd" "Jasminder" ...
    ##  $ technical: num [1:1136] 2 3 1 NA 9 NA 8 NA 10 NA ...
    ##  $ result   : chr [1:1136] "IN" "IN" "IN" "IN" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   series = col_double(),
    ##   ..   episode = col_double(),
    ##   ..   baker = col_character(),
    ##   ..   technical = col_double(),
    ##   ..   result = col_character()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
bakers <- bakers %>%
  separate(baker_name, into = c("baker", "last name"), sep = " ")
```

\#combine bakers & bake

``` r
combined_data <- bakers %>%
  left_join(bakes, by = c("baker", "series")) 
```

\#combine all

``` r
final_combine <- left_join(combined_data, results, by = c("baker", "episode", "series")) %>%
  janitor::clean_names() %>%
  relocate(baker, series, episode)

write_csv(final_combine, "./gbb_datasets/final_combine.csv")
```

\#Describe your data cleaning process, including any questions you have
or choices you made. Briefly discuss the final dataset.

The data cleaning process began by importing the `bakers.csv`,
`bakes.csv`, and `results.csv` datasets, skipping the first two lines of
`results.csv` as they didn’t contain column names. I checked the
structure of each dataset to ensure consistent variable types, renaming
columns for clarity (e.g., `Baker.Name` to `baker_name`). In the
`bakers` dataset, I split `baker_name` into `baker` and `last_name` for
easier merging. I then combined the datasets using `left_join()` on
`baker`, `series`, and `episode`. After merging, I applied
`janitor::clean_names()` to standardize column names and reordered key
variables. The final dataset is tidy and includes important variables
like `baker`, `series`, `episode`, and performance details such as
`technical_rank` and `star_baker`, ready for analysis.

# Filter for seasons 5 through 10 and where result is “Star Baker”

``` r
star_bakers <- final_combine %>%
  filter(series >= 5 & series <= 10,result %in% c("STAR BAKER","WINNER")) %>%
  select(baker, series, episode,result) %>%
arrange(series, episode)
star_bakers
```

    ## # A tibble: 40 × 4
    ##    baker   series episode result    
    ##    <chr>    <dbl>   <dbl> <chr>     
    ##  1 Nancy        5       1 STAR BAKER
    ##  2 Richard      5       2 STAR BAKER
    ##  3 Luis         5       3 STAR BAKER
    ##  4 Richard      5       4 STAR BAKER
    ##  5 Kate         5       5 STAR BAKER
    ##  6 Chetna       5       6 STAR BAKER
    ##  7 Richard      5       7 STAR BAKER
    ##  8 Richard      5       8 STAR BAKER
    ##  9 Richard      5       9 STAR BAKER
    ## 10 Nancy        5      10 WINNER    
    ## # ℹ 30 more rows

\#Based on the table, Richard stood out as a highly consistent
contestant in Season 5, earning the title of Star Baker an impressive
five times, which made him a predictable contender for the overall win.
However, despite his strong performance, Nancy ultimately emerged as the
winner of Season 5, which could be considered a surprise given Richard’s
consistent dominance throughout the season. This dynamic highlights how,
even with strong individual performances, the competition can still
yield unexpected results.

\#convert values to numeric

``` r
viewers <- read_csv("gbb_datasets/viewers.csv")
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
data_cleaned <- viewers %>%
  mutate(across(starts_with("Series"), ~ as.numeric(as.character(.))))
print(data_cleaned)
```

    ## # A tibble: 10 × 11
    ##    Episode `Series 1` `Series 2` `Series 3` `Series 4` `Series 5` `Series 6`
    ##      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>
    ##  1       1       2.24       3.1        3.85       6.6        8.51       11.6
    ##  2       2       3          3.53       4.6        6.65       8.79       11.6
    ##  3       3       3          3.82       4.53       7.17       9.28       12.0
    ##  4       4       2.6        3.6        4.71       6.82      10.2        12.4
    ##  5       5       3.03       3.83       4.61       6.95       9.95       12.4
    ##  6       6       2.75       4.25       4.82       7.32      10.1        12  
    ##  7       7      NA          4.42       5.1        7.76      10.3        12.4
    ##  8       8      NA          5.06       5.35       7.41       9.02       11.1
    ##  9       9      NA         NA          5.7        7.41      10.7        12.6
    ## 10      10      NA         NA          6.74       9.45      13.5        15.0
    ## # ℹ 4 more variables: `Series 7` <dbl>, `Series 8` <dbl>, `Series 9` <dbl>,
    ## #   `Series 10` <dbl>

# average viewership season 1

``` r
average_viewership_season_1 <- mean(data_cleaned$`Series 1`, na.rm = TRUE)
print(average_viewership_season_1)
```

    ## [1] 2.77

\#For Season 1, the average viewership was 2.77

# average viewership season 5

``` r
average_viewership_season_5 <- mean(data_cleaned$`Series 5`, na.rm = TRUE)
print(average_viewership_season_5)
```

    ## [1] 10.0393

\#For Season 5, the average viewership was 10.0393
